[project]
name = "grove"
version = "1.0.0-dev"
dependencies = [
    "django~=5.0",
    "plastron-utils~=4.0",
    "rdflib~=7.0",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-django",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "grove.settings"
